InventoryManagerment/Models/WINFORMS/NOTES.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace InventoryManagerment.Models.WINFORMS
{
    [Table("NOTES")]
    public partial class NOTES
    {      
        public string CUSTOMER { get; set; }
        [Key]
        public string ID { get; set; }
        public int STT { get; set; }
        public string TIME { get; set; }
        public string STAFF { get; set; }
        public string NOTE { get; set; }
        public string STATUS { get; set; }
    }
}

InventoryManagerment/Controllers/NoteController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace InventoryManagerment.Controllers
{
    public class NoteController : AdminController
    {
        // GET: Note
        public ActionResult Index(string searchString, string noteGhiChu,DateTime? dateNote,string status,int page=1,int pageSize =10)
        {
            TempData[Common.CommonConstants.PAGE_NAME] = "Số xuất";
            ViewBag.Title = "Tuấn Hoan - Danh Sách Sổ Xuất";
            ViewBag.searchString = searchString;
            if (dateNote.HasValue)
            {
                ViewBag.dateNote = dateNote.Value.ToString("yyyy-MM-dd");
            }            
            if(pageSize > 10)
            {
                ViewBag.pageSize = pageSize;
            }
            ViewBag.noteGhiChu = noteGhiChu;
            ViewBag.status = status;
            var model = new DataAccess2().ListAllNotesToPagedList(searchString,noteGhiChu,dateNote,status, page, pageSize);
            return View(model);
        }
        [HttpGet]
        public JsonResult GetDetailNote(string code)
        {
            string note = new DataAccess2().GetNote(code);
            return Json(note, JsonRequestBehavior.AllowGet);
        }
    }
}

InventoryManagerment/Views/Note/Index.cshtml
@using PagedList;
@using PagedList.Mvc;
@model IPagedList<InventoryManagerment.Models.WINFORMS.NOTES>
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
    string GetNote(string text)
    {
        string chuoican = "";
        for (int i = 60; i < text.Length; i++)
        {
            if (text[i] == ' ')
            {
                chuoican = text.Substring(0, i);
                break;
            }
            else
            {
                continue;
            }
        }
        return chuoican;
    }
}
<!--Modal Note-->
<div class="modal fade" id="ghichu" tabindex="-1" role="dialog" aria-labelledby="ghichuLabel" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title font-weight-normal" id="ghichuLabel">Ghi chú</h5>
                <button type="button" class="btn-close text-dark" data-bs-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
            </div>
        </div>
    </div>
</div>
<div class="row" id="productList">
    <div class="col-12">
        <div class="card my-4">
            <div class="card-header p-0 position-relative mt-n4 mx-3 z-index-2">
                <div class="row bg-gradient-primary shadow-primary border-radius-lg pt-4 pb-3">
                    <div class="col-6">
                        <h6 class="mb-0 text-white text-capitalize ps-3">Danh sách Sổ xuất</h6>
                    </div>
                    <div class="col-6 text-end">
                        <a class="btn bg-gradient-dark mb-0 text-white text-capitalize" data-bs-toggle="modal" data-bs-target="#searchModal"><i class="material-icons">search</i></a>
                    </div>
                </div>
            </div>
            <div class="card-body px-0 pb-2">
                <div class="px-2 mb-1">
                    <!-- Modal -->
                    <div class="modal fade" id="searchModal" tabindex="-1" role="dialog" aria-labelledby="searchtitleModal" aria-hidden="true">
                        <div class="modal-dialog modal-dialog-centered" role="document">
                            <div class="modal-content">
                                <div class="modal-header">
                                    <h5 class="modal-title font-weight-normal" id="searchtitleModal">Tìm kiếm sổ xuất</h5>
                                    <button type="button" class="btn-close text-dark" data-bs-dismiss="modal" aria-label="Close">
                                        <span aria-hidden="true">&times;</span>
                                    </button>
                                </div>
                                <div class="modal-body">
                                    @using (Html.BeginForm("Index", "Note", method: FormMethod.Get))
                                    {
                                        <div class="input-group mb-3">
                                            <div class="input-group input-group-static mb-4">
                                                <input placeholder="Nhập tên khách hàng" type="text" class="form-control" onfocus="focused(this)" onfocusout="defocused(this)" value="@ViewBag.searchString" name="searchString">
                                            </div>
                                            <div class="input-group input-group-static mb-4">
                                                <textarea placeholder="Nhập ghi chú" type="text" class="form-control" onfocus="focused(this)" onfocusout="defocused(this)" name="noteGhiChu">@ViewBag.noteGhiChu</textarea>
                                            </div>
                                            <div class="input-group input-group-static mb-4">
                                                <select name="status" class="form-control">
                                                    <option value="Tất cả">Tất cả</option>
                                                    <option value="Đã Thanh Toán">Đã Thanh Toán</option>
                                                    <option value="Chưa Thanh Toán (Có HĐ)">Chưa Thanh Toán (Có HĐ)</option>
                                                    <option value="Chưa Thanh Toán (Không HĐ)">Chưa Thanh Toán (Không HĐ)</option>
                                                </select>
                                            </div>
                                            <div class="input-group input-group-static mb-4">
                                                <input type="date" class="form-control" onfocus="focused(this)" onfocusout="defocused(this)" value="@ViewBag.dateNote" id="dateNote" name="dateNote">
                                            </div>
                                            <div class="input-group input-group-static mb-4">
                                                <select name="pageSize" class="form-control">
                                                    <option value="10">Số dòng hiển thị</option>
                                                    @for (int i = 15; i <= 100; i += 5)
                                                    {
                                                        <option value="@i">@i</option>
                                                    }
                                                </select>
                                            </div>
                                        </div>
                                        <button id="btnSearch" type="submit" class="btn btn-icon btn-3 btn-outline-primary input-group-outline input-group-text">
                                            <span class="btn-inner--icon"><i class="material-icons">search</i></span>
                                            <span class="btn-inner--text">Tìm kiếm</span>
                                        </button>
                                    }
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="table-responsive p-0">
                    <table class="table align-items-center mb-0" id="tbl_Product">
                        <thead>
                            <tr>
                                <th class="text-center text-uppercase text-secondary text-xs font-weight-bolder opacity-7">Ngày bán</th>
                                <th class="text-center text-uppercase text-secondary text-xs font-weight-bolder opacity-7">Tên khách hàng</th>
                                <th class="text-center text-uppercase text-secondary text-xs font-weight-bolder opacity-7">Ghi chú</th>
                                <th class="text-center text-uppercase text-secondary text-xs font-weight-bolder opacity-7">Người giao</th>
                                <th class="text-center text-uppercase text-secondary text-xs font-weight-bolder opacity-7">Trạng thái</th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach (var item in Model)
                            {
                                <tr id="row_@item.ID">
                                    @*<td>
                                            <div class="d-flex px-2 py-1">
                                                <div class="d-flex flex-column justify-content-center">
                                                    <h6 class="mb-0 text-sm">@item.Name</h6>
                                                    @if (item.CategoryID.HasValue)
                                                    {
                                                        <p class="text-xs text-secondary mb-0">@GetCategoryName(item.CategoryID)</p>
                                                    }
                                                </div>
                                            </div>
                                        </td>*@
                                    <td class="align-middle text-center">
                                        <span class="text-secondary text-xs font-weight-bold">@item.TIME</span>
                                    </td>
                                    <td class="align-middle text-center">
                                        <span class="text-secondary text-xs font-weight-bold">@item.CUSTOMER</span>
                                    </td>
                                    <td>
                                        @if (item.NOTE.Length > 60)
                                        {
                                            <a onclick="showNote(this)" id="@item.ID" href="javascript:;" data-bs-toggle="modal" data-bs-target="#ghichu"><span class="text-secondary text-xs font-weight-bold">@GetNote(item.NOTE)</span>  ...</a>
                                        }
                                        else
                                        {
                                    <a onclick="showNote(this)" id="@item.ID" href="javascript:;" data-bs-toggle="modal" data-bs-target="#ghichu"><span class="text-secondary text-xs font-weight-bold">@item.NOTE</span></a>
                                        }

                                    </td>
                                    <td class="align-middle text-center">
                                        <span class="text-secondary text-xs font-weight-bold">@item.STAFF</span>
                                    </td>
                                    <td class="align-middle text-center">
                                        <span class="text-secondary text-xs font-weight-bold">@item.STATUS</span>
                                    </td>

                                </tr>
                            }
                        </tbody>
                    </table>
                    <div style="text-align:center">
                        <div style="display:inline-block" id="listPaginationProduct">
                            @Html.PagedListPager(Model, page => Url.Action("Index", new { page, searchString = ViewBag.searchString, noteGhiChu = ViewBag.noteGhiChu, dateNote = ViewBag.dateNote, status = ViewBag.status, pageSize = ViewBag.pageSize }))
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
@section jsFooter{
    <script>
        $(document).ready(function () {
            addClasslist();
        });
        function showNote(element) {
            var code = $(element).attr('id');
            $.ajax({
                url:'/Note/GetDetailNote/',
                type: 'GET',
                data: { code: code },
                success: function (result) {
                    $('#ghichu').find('.modal-body').html(result);
                }
            })
        }
        function addClasslist() {
            $('#listPaginationProduct ul li').each(function () {
                $(this).addClass('page-item');
                $(this).find('a').addClass('page-link')
            });
        }
    </script>
}